spring:
  profiles:
    active: dev
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  thymeleaf:
    cache: false # 建议关闭缓存
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
  mvc:
    dispatch-options-request: true #设置请求方式OPTIONS生效
  servlet:
    multipart:
      max-file-size: 20Mb
      max-request-size: 50Mb

server:
  tomcat:
    uri-encoding: UTF-8
    max-http-header-size: 65536 #bytes 64k
  servlet:
    context-path: /scaffold
    max-http-header-size: 65536 #bytes 64k

druid:
  account: admin
  password: 123456

global:
  uploadPath: /tmp/scaffold/
  swaggerShow: false


mybatis:
  mapper-locations: classpath:mapper/*.xml # xml文件所在路径
  type-aliases-package: com.dj.scaffold.dao # dao所在的包名
